
INSERT INTO public.SR_TASK_PUPIL  ( SRP_ID,SRTA_ID, COUNT,STATUS) VALUES           ( 2, 1, 4, 'Done');
INSERT INTO public.SR_TASK_PUPIL  ( SRP_ID,SRTA_ID, COUNT,STATUS)  VALUES             ( 2, 2, 3, 'Done');
INSERT INTO public.SR_TASK_PUPIL ( SRP_ID,SRTA_ID, COUNT,STATUS) VALUES            ( 2, 1, 2, 'Done');
